#! /bin/bash

java -jar ./lib/antlr-4.9.2-complete.jar expr.g4 -no-listener -no-visitor -o ./src/parser
javac  -cp ./lib/antlr-4.9.2-complete.jar:./src ./src/Main.java -d ./bin
sed -i '49s/.*//' ./src/Main.java
java -cp ./lib/antlr-4.9.2-complete.jar:./bin Main $1
