#! /bin/bash

function test (){
for f in tests/success/*; do
    if  [ ! -d "$f" ]; 
    then 
        echo "Test de $f"
        java -jar ./lib/antlr-4.9.2-complete.jar expr.g4 -no-listener -no-visitor -o ./src/parser
        javac  -cp ./lib/antlr-4.9.2-complete.jar:./src ./src/Main.java -d ./bin
        sed -i '49s/.*/frame.dispose();/' ./src/Main.java
        java -cp ./lib/antlr-4.9.2-complete.jar:./bin Main $f
        echo "✅ Un mot est proposée !"
    fi
done
for f in tests/fail/*; do
    if  [ ! -d "$f" ]; 
    then 
        echo "Test de $f"
        ./setup ./"$f" 
        echo "🔴 Aucun mot n'est proposée"
    fi
done
}

test