let
var a := "un"
var b := 2
in
end

let 
var c := 2
var c := "deux"
var b := 6
in
    let 
    type club = {a : int}
    type club2 = {a : int, b : string, c : int}
    type club3= club2
    type club4= clubInconnu
    type tableau = array of int
    var d := 3
    var d := 4
    var e := 5
    var f := tableau ["salut"] of 0
    var f := tableau [3] of 0
    var g := club2 {a = 10, b ="salut" , c = 3}
    in
    end
end