let 
    type club = {a : int}
    type club2 = {a : int, b : string, c : int}
    type cool = {a : club2, b : int}
    type club3= club2
    type tableau = array of int
    type tabCool = array of cool
    type pasCool = {a: tabCool, b: int}
    var d := 3
    var d := 4
    var e := 5
    var f := tableau ["salut"] of 0
    var f := tableau [3] of 0
    var g := club2 {a = 10, b ="salut" , c = 3}
    var h := cool {a=g, b=10}
    var tab := tabCool [3] of h
    var dict : pasCool := pasCool { a = tab, b = 5}

in
    f[0] := 1;
    tab[2].a := g
    

end